"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {signInAnonymously} from "firebase/auth";
import {auth} from "@/lib/firebase/client";
import {createServiceRequest,type ServiceRequest} from "@/lib/firebase/data";
const serviceOptions=["Auto Mechanical","Auto Electrical","Breakdown & Fleet","Routine Service","Towing / Recovery","Onsite Auto-Electrical"];
export default function BookPage(){const[submitted,setSubmitted]=useState(false),[reference,setReference]=useState(""),[pending,setPending]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[prefill,setPrefill]=useState("");
useEffect(()=>{const value=new URLSearchParams(window.location.search).get("service");if(value)setPrefill(value)},[]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError("");const f=new FormData(e.currentTarget);const service=String(f.get("service")||"").trim(),name=String(f.get("name")||"").trim(),phone=String(f.get("phone")||"").trim(),vehicle=String(f.get("vehicle")||"").trim(),registration=String(f.get("registration")||"").trim(),preferred=String(f.get("preferred")||"").trim(),location=String(f.get("location")||"").trim(),notes=String(f.get("notes")||"").trim();if(!service||!name||!phone||!vehicle){setError("Please add the service, your name, phone and vehicle.");setBusy(false);return}try{let customerId:string|undefined;try{customerId=(await signInAnonymously(auth)).user.uid}catch{}const offline=!navigator.onLine;const request:Omit<ServiceRequest,"id">={customerId,createdAt:new Date().toISOString(),customerName:name,phone,service,vehicle,registration,preferred,location,notes,status:"Submitted",source:offline?"offline":"online"};const{id,writePromise}=createServiceRequest(request);setReference(id);if(offline){void writePromise.catch(()=>{});setPending(true)}else{await writePromise;setPending(false)}localStorage.setItem("atlas:lastRequest",id);setSubmitted(true);e.currentTarget.reset()}catch{setError("The request could not be confirmed online. Check the connection and try again, or call the workshop.")}finally{setBusy(false)}}
if(submitted)return <main className="formPage"><div className="formWrap"><div className="formTop"><Link href="/" className="brand compact"><span className="brandBadge">ASC</span><span><strong>ATLAS SERVICE CENTRE</strong><small>Your Auto Mechanical & Electrical Specialists</small></span></Link></div><section className="formCard confirmation"><span className="eyebrow">{pending?"Saved on this phone":"Request submitted"}</span><div className="confirmMark">{pending?"OFFLINE":"✓"}</div><h1>{pending?"Saved locally.":"Request received."}</h1><p>{pending?"Your request is stored on this device. Reconnect to allow Firebase to synchronize it; until then, the workshop has not received it.":"Your request has been written to the Atlas request queue. A request is not a confirmed appointment until the workshop accepts it."}</p><strong>Reference #{reference.slice(0,8).toUpperCase()}</strong><div className="actions centered"><Link href={"/orders/"+reference} className="button buttonPrimary">Track request</Link><Link href="/" className="button buttonLight">Back to Atlas</Link></div></section></div></main>;
return <main className="formPage"><div className="formWrap"><div className="formTop"><Link href="/" className="brand compact"><span className="brandBadge">ASC</span><span><strong>ATLAS SERVICE CENTRE</strong><small>Your Auto Mechanical & Electrical Specialists</small></span></Link><a className="button buttonDark" href="tel:+2673928833">Call workshop</a></div><section className="formIntro"><span className="eyebrow">Service request</span><h1>Tell the workshop what you need.</h1><p>Use this form for routine service, mechanical, auto-electrical, towing, recovery or onsite assistance.</p></section><form className="requestForm" onSubmit={submit}><section className="formCard"><h2>1 · Request</h2><label>Service<select name="service" defaultValue={prefill||"Auto Mechanical"}>{serviceOptions.map(v=><option key={v}>{v}</option>)}</select></label><label>Vehicle / fleet unit<input name="vehicle" placeholder="e.g. Toyota Hilux / Volvo FH" required/></label><label>Registration / fleet number<input name="registration" placeholder="Optional"/></label><label>What do you need?<textarea name="notes" placeholder="Describe the fault, service or breakdown symptoms."/></label></section><section className="formCard"><h2>2 · Contact</h2><label>Your name<input name="name" autoComplete="name" required/></label><label>Phone / WhatsApp<input name="phone" type="tel" autoComplete="tel" required/></label><label>Preferred date / time<input name="preferred" placeholder="e.g. tomorrow morning"/></label><label>Vehicle location<input name="location" placeholder="Workshop / yard / roadside landmark"/></label><p className="truthNote">We will use these details to review the request. Sending this form does not by itself confirm an appointment or guarantee response time.</p>{error&&<p className="notice" role="alert">{error}</p>}<button className="button buttonPrimary submitButton" type="submit" disabled={busy}>{busy?"Saving request…":"Send service request"}</button></section></form></div></main>}
