"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
const images=["/atlas-assets/WhatsApp Image 2026-09-23 at 14.12.46.jpeg","/atlas-assets/WhatsApp Image 2026-09-23 at 14.16.14.jpeg","/atlas-assets/WhatsApp Image 2026-09-23 at 14.16.15.jpeg","/atlas-assets/WhatsApp Image 2026-09-23 at 14.16.16.jpeg"];
const services=[["Auto Mechanical","Engine overhauls · Gearboxes & differentials · Brakes · Suspension & steering · Routine servicing"],["Auto Electrical","Starter motors · Alternators · Rewiring · Computerized diagnostics · Fault-code work"],["Breakdown & Fleet","24-hour towing/recovery · Onsite assistance · Fleet maintenance · Fluid & maintenance checks"]];
export default function Home(){const[slide,setSlide]=useState(0);useEffect(()=>{const id=window.setInterval(()=>setSlide(v=>(v+1)%images.length),5000);return()=>window.clearInterval(id)},[]);return <main className="atlasSite">
<header className="siteHeader"><div className="container headerInner"><Link href="/" className="brand" aria-label="Atlas Service Centre home"><span className="brandBadge">ASC</span><span><strong>ATLAS SERVICE CENTRE</strong><small>Your Auto Mechanical & Electrical Specialists</small></span></Link><nav className="navLinks"><a href="#services">Services</a><a href="#workshop">Workshop</a><a href="#contact">Contact</a></nav><Link href="/book" className="button buttonPrimary">Book Service</Link></div></header>
<div className="urgentBar"><div className="container urgentInner"><strong>Need urgent help?</strong><span>Recovery & onsite assistance</span><div><a href="tel:+26771621734">Call 716 21734</a><a href="tel:+26774225346">Call 742 25346</a></div></div></div>
<section className="hero"><div className="container heroGrid"><div className="heroCopy"><span className="eyebrow">Gaborone West Industrial · Plot 14441, Unit 1</span><h1>Keep your<br/><em>vehicles moving.</em></h1><p>Industrial-grade mechanical and auto-electrical servicing for commercial transport, fleets, light trucks and private vehicles.</p><div className="actions"><Link href="/book" className="button buttonPrimary">Book a service</Link><a href="tel:+2673928833" className="button buttonDark">Call workshop</a></div><div className="heroFacts"><span>MON–FRI 07:30–17:30</span><span>SAT 08:00–13:00</span><span>SUN CLOSED</span></div></div><div className="heroMedia"><video autoPlay muted loop playsInline preload="metadata" poster={images[0]} aria-label="Atlas Service Centre workshop video"><source src="/atlas-assets/atlas.mp4" type="video/mp4"/><source src="/atlas-assets/WhatsApp Video 2026-09-23 at 14.12.45.mp4" type="video/mp4"/></video><div className="mediaTag">REAL ATLAS WORKSHOP</div></div></div></section>
<section className="serviceStrip" id="services"><div className="container"><div className="sectionIntro"><span className="eyebrow">What we handle</span><h2>One workshop.<br/>Three core divisions.</h2></div><div className="serviceGrid">{services.map(([title,copy],i)=><article className="serviceCard" key={title}><span className="serviceNumber">0{i+1}</span><h3>{title}</h3><p>{copy}</p><Link href={"/book?service="+encodeURIComponent(title)} className="textLink">Request this service →</Link></article>)}</div></div></section>
<section className="evidenceSection" id="workshop"><div className="container evidenceGrid"><div className="gallery"><img src={images[slide]} alt="Atlas Service Centre workshop" /><div className="galleryControls" aria-label="Workshop photos">{images.map((_,i)=><button key={i} className={i===slide?"active":""} onClick={()=>setSlide(i)} aria-label={"Show workshop photo "+(i+1)}/>)}</div></div><div className="evidenceCopy"><span className="eyebrow">The workshop, not stock photography</span><h2>Real work.<br/>Real equipment.<br/>Real people.</h2><p>We use the workshop itself as the proof point: vehicles, diagnostics, electrical work, engines and recovery capability.</p><div className="evidenceList"><strong>Heavy & light duty</strong><strong>Mechanical + electrical</strong><strong>Fleet-focused servicing</strong></div></div></div></section>
<section className="requestBand"><div className="container requestInner"><div><span className="eyebrow">When downtime matters</span><h2>Start the job<br/>from your phone.</h2><p>Send a service, towing or onsite auto-electrical request. We show the workshop workflow clearly instead of pretending an online form is already a confirmed job.</p></div><div className="requestActions"><Link href="/book" className="button buttonPrimary">Start a request</Link><a href="tel:+2673928833" className="button buttonLight">+267 392 8833</a></div></div></section>
<section className="locationSection" id="contact"><div className="container locationGrid"><div><span className="eyebrow">Find the workshop</span><h2>Gaborone West Industrial.</h2><p>Plot 14441, Unit 1, Kamushongo Road, Gaborone West Industrial, Gaborone, Botswana.</p><div className="hours"><strong>Hours</strong><span>Mon–Fri · 07:30–17:30</span><span>Sat · 08:00–13:00</span><span>Sun · Closed</span></div><div className="actions"><a className="button buttonPrimary" href="tel:+2673928833">Call +267 392 8833</a><a className="button buttonLight" href="mailto:atlascentre@gmail.com">atlascentre@gmail.com</a></div></div><div className="contactCard"><span className="contactIcon">ASC</span><strong>Atlas Service Centre</strong><small>Your Auto Mechanical & Electrical Specialists</small><a href="https://www.google.com/maps/search/?api=1&query=Plot+14441+Kamushongo+Road+Gaborone+West+Industrial+Gaborone+Botswana" target="_blank" rel="noreferrer">Open location in Maps →</a></div></div></section>
<footer className="footer"><div className="container footerInner"><div><strong>ATLAS SERVICE CENTRE</strong><span>Atlas Heavy & Light Duty Workshop T/A Atlas Service Centre</span></div><div><a href="tel:+2673928833">+267 392 8833</a><span>Gaborone · Botswana</span></div></div></footer><div className="mobileEmergency"><a href="tel:+26771621734">URGENT · 716 21734</a><Link href="/book">BOOK SERVICE</Link></div></main>}
