"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const services = [
  ["Auto Mechanical", "Engine overhauls · Gearboxes & differentials · Brakes · Suspension & steering · Routine servicing"],
  ["Auto Electrical", "Starter motors · Alternators · Rewiring · Computerized diagnostics · Fault-code work"],
  ["Breakdown & Fleet", "24-hour towing/recovery · Onsite assistance · Fleet maintenance · Fluid & maintenance checks"],
];

const illustrations = [
  { title: "Heavy & Light Duty", label: "Mechanical", copy: "Engines, gearboxes, brakes, suspension and routine servicing.", kind: "mechanical" },
  { title: "Auto Electrical", label: "Electrical", copy: "Starters, alternators, rewiring and computerized fault finding.", kind: "electrical" },
  { title: "Diagnostics", label: "Diagnostics", copy: "Find the fault, understand the system, then get the vehicle moving.", kind: "diagnostics" },
  { title: "Engines & Recovery", label: "Recovery", copy: "Engine work, heavy components and recovery capability under one roof.", kind: "recovery" },
] as const;

function AtlasIllustration({ kind }: { kind: (typeof illustrations)[number]["kind"] }) {
  const common = { fill: "none", stroke: "currentColor", strokeWidth: 7, strokeLinecap: "round" as const, strokeLinejoin: "round" as const };

  if (kind === "electrical") return <svg viewBox="0 0 600 420" role="img" aria-label="Atlas auto electrical illustration" className="atlasIllustration"><rect x="52" y="52" width="496" height="316" rx="28" fill="#101010" stroke="#00873D" strokeWidth="5"/><path d="M110 282h220" stroke="#00873D" strokeWidth="18" strokeLinecap="round"/><rect x="120" y="145" width="185" height="115" rx="14" fill="#171717" stroke="#fff" strokeWidth="7"/><path d="M155 145v-22h40v22M230 145v-22h40v22" {...common}/><path d="M168 204h85" stroke="#7bd89e" strokeWidth="10" strokeLinecap="round"/><path d="M392 110l-48 102h42l-34 92 91-124h-49z" fill="#F39C12" stroke="#fff" strokeWidth="6" strokeLinejoin="round"/><circle cx="414" cy="285" r="45" fill="#00873D"/><path d="M393 285h42M414 264v42" stroke="#fff" strokeWidth="7" strokeLinecap="round"/></svg>;

  if (kind === "diagnostics") return <svg viewBox="0 0 600 420" role="img" aria-label="Atlas diagnostics illustration" className="atlasIllustration"><rect x="52" y="52" width="496" height="316" rx="28" fill="#101010" stroke="#00873D" strokeWidth="5"/><path d="M115 278h370" stroke="#00873D" strokeWidth="16" strokeLinecap="round"/><path d="M145 278l20-72h190l35 72" fill="#171717" stroke="#fff" strokeWidth="7" strokeLinejoin="round"/><circle cx="207" cy="278" r="20" fill="#00873D" stroke="#fff" strokeWidth="6"/><circle cx="385" cy="278" r="20" fill="#00873D" stroke="#fff" strokeWidth="6"/><rect x="235" y="138" width="170" height="88" rx="10" fill="#171717" stroke="#7bd89e" strokeWidth="6"/><path d="M258 202l26-28 24 18 38-42 31 28" {...common} stroke="#F39C12"/><path d="M454 112v74M417 149h74" stroke="#fff" strokeWidth="7" strokeLinecap="round"/></svg>;

  if (kind === "recovery") return <svg viewBox="0 0 600 420" role="img" aria-label="Atlas recovery and engine illustration" className="atlasIllustration"><rect x="52" y="52" width="496" height="316" rx="28" fill="#101010" stroke="#00873D" strokeWidth="5"/><path d="M104 286h390" stroke="#00873D" strokeWidth="16" strokeLinecap="round"/><path d="M126 270v-92h154l62 48v44z" fill="#171717" stroke="#fff" strokeWidth="7" strokeLinejoin="round"/><path d="M280 178v48h62" {...common}/><circle cx="178" cy="286" r="27" fill="#00873D" stroke="#fff" strokeWidth="7"/><circle cx="350" cy="286" r="27" fill="#00873D" stroke="#fff" strokeWidth="7"/><path d="M342 225h74l54 45" {...common}/><path d="M444 142v92M444 142h42M444 234h42" stroke="#F39C12" strokeWidth="8" strokeLinecap="round"/><path d="M466 234c-8 25-8 42 8 52" stroke="#fff" strokeWidth="6" fill="none"/></svg>;

  return <svg viewBox="0 0 600 420" role="img" aria-label="Atlas mechanical workshop illustration" className="atlasIllustration"><rect x="52" y="52" width="496" height="316" rx="28" fill="#101010" stroke="#00873D" strokeWidth="5"/><path d="M105 300h390" stroke="#00873D" strokeWidth="16" strokeLinecap="round"/><path d="M154 278V154h292v124" {...common} stroke="#fff"/><path d="M180 154v-40h70v40M350 154v-40h70v40" {...common} stroke="#7bd89e"/><rect x="215" y="200" width="170" height="70" rx="14" fill="#171717" stroke="#fff" strokeWidth="7"/><circle cx="250" cy="235" r="16" fill="#00873D"/><circle cx="340" cy="235" r="16" fill="#F39C12"/><path d="M185 300v-34M415 300v-34" stroke="#fff" strokeWidth="10" strokeLinecap="round"/><path d="M470 126l-34 54h29l-25 50 58-75h-31z" fill="#F39C12" stroke="#fff" strokeWidth="5" strokeLinejoin="round"/></svg>;
}

export default function Home() {
  const [slide, setSlide] = useState(0);
  useEffect(() => { const id = window.setInterval(() => setSlide((v) => (v + 1) % illustrations.length), 5000); return () => window.clearInterval(id); }, []);
  const current = illustrations[slide];

  return <main className="atlasSite">
<header className="siteHeader"><div className="container headerInner"><Link href="/" className="brand" aria-label="Atlas Service Centre home"><span className="brandBadge">ASC</span><span><strong>ATLAS SERVICE CENTRE</strong><small>Your Auto Mechanical & Electrical Specialists</small></span></Link><nav className="navLinks"><a href="#services">Services</a><a href="#workshop">Workshop</a><a href="#contact">Contact</a></nav><Link href="/book" className="button buttonPrimary">Book Service</Link></div></header>
<div className="urgentBar"><div className="container urgentInner"><strong>Need urgent help?</strong><span>Recovery & onsite assistance</span><div><a href="tel:+26771621734">Call 716 21734</a><a href="tel:+26774225346">Call 742 25346</a></div></div></div>
<section className="hero"><div className="container heroGrid"><div className="heroCopy"><span className="eyebrow">Gaborone West Industrial · Plot 14441, Unit 1</span><h1>Keep your<br/><em>vehicles moving.</em></h1><p>Industrial-grade mechanical and auto-electrical servicing for commercial transport, fleets, light trucks and private vehicles.</p><div className="actions"><Link href="/book" className="button buttonPrimary">Book a service</Link><a href="tel:+2673928833" className="button buttonDark">Call workshop</a></div><div className="heroFacts"><span>MON–FRI 07:30–17:30</span><span>SAT 08:00–13:00</span><span>SUN CLOSED</span></div></div><div className="heroMedia"><video autoPlay muted loop playsInline preload="metadata" aria-label="Atlas Service Centre workshop video"><source src="/atlas-assets/atlas.mp4" type="video/mp4"/></video><div className="mediaTag">REAL ATLAS WORKSHOP</div></div></div></section>
<section className="serviceStrip" id="services"><div className="container"><div className="sectionIntro"><span className="eyebrow">What we handle</span><h2>One workshop.<br/>Three core divisions.</h2></div><div className="serviceGrid">{services.map(([title,copy],i)=><article className="serviceCard" key={title}><span className="serviceNumber">0{i+1}</span><h3>{title}</h3><p>{copy}</p><Link href={"/book?service="+encodeURIComponent(title)} className="textLink">Request this service →</Link></article>)}</div></div></section>
<section className="evidenceSection" id="workshop"><div className="container evidenceGrid"><div className="illustrationCarousel"><div className="illustrationFrame"><div className="illustrationArt"><AtlasIllustration kind={current.kind}/></div><div className="illustrationCaption"><span>{current.label}</span><strong>{current.title}</strong><p>{current.copy}</p></div><button className="carouselArrow carouselPrev" onClick={()=>setSlide((slide-1+illustrations.length)%illustrations.length)} aria-label="Previous capability">←</button><button className="carouselArrow carouselNext" onClick={()=>setSlide((slide+1)%illustrations.length)} aria-label="Next capability">→</button></div><div className="galleryControls" aria-label="Atlas capability illustrations">{illustrations.map((item,i)=><button key={item.kind} className={i===slide?"active":""} onClick={()=>setSlide(i)} aria-label={"Show "+item.title+" illustration"}/>)}</div><div className="realEvidenceNote">Illustrated capability guide · real workshop footage above</div></div><div className="evidenceCopy"><span className="eyebrow">The workshop, not stock photography</span><h2>Real work.<br/>Real equipment.<br/>Real people.</h2><p>We use the workshop itself as the proof point: vehicles, diagnostics, electrical work, engines and recovery capability.</p><div className="evidenceList"><strong>Heavy & light duty</strong><strong>Mechanical + electrical</strong><strong>Fleet-focused servicing</strong></div></div></div></section>
<section className="requestBand"><div className="container requestInner"><div><span className="eyebrow">When downtime matters</span><h2>Start the job<br/>from your phone.</h2><p>Send a service, towing or onsite auto-electrical request. We show the workshop workflow clearly instead of pretending an online form is already a confirmed job.</p></div><div className="requestActions"><Link href="/book" className="button buttonPrimary">Start a request</Link><a href="tel:+2673928833" className="button buttonLight">+267 392 8833</a></div></div></section>
<section className="locationSection" id="contact"><div className="container locationGrid"><div><span className="eyebrow">Find the workshop</span><h2>Gaborone West Industrial.</h2><p>Plot 14441, Unit 1, Kamushongo Road, Gaborone West Industrial, Gaborone, Botswana.</p><div className="hours"><strong>Hours</strong><span>Mon–Fri · 07:30–17:30</span><span>Sat · 08:00–13:00</span><span>Sun · Closed</span></div><div className="actions"><a className="button buttonPrimary" href="tel:+2673928833">Call +267 392 8833</a><a className="button buttonLight" href="mailto:atlascentre@gmail.com">atlascentre@gmail.com</a></div></div><div className="contactCard"><span className="contactIcon">ASC</span><strong>Atlas Service Centre</strong><small>Your Auto Mechanical & Electrical Specialists</small><a href="https://www.google.com/maps/search/?api=1&query=Plot+14441+Kamushongo+Road+Gaborone+West+Industrial+Gaborone+Botswana" target="_blank" rel="noreferrer">Open location in Maps →</a></div></div></section>
<footer className="footer"><div className="container footerInner"><div><strong>ATLAS SERVICE CENTRE</strong><span>Atlas Heavy & Light Duty Workshop T/A Atlas Service Centre</span></div><div><a href="tel:+2673928833">+267 392 8833</a><span>Gaborone · Botswana</span></div></div></footer><div className="mobileEmergency"><a href="tel:+26771621734">URGENT · 716 21734</a><Link href="/book">BOOK SERVICE</Link></div></main>;
}
