"use client";
import {GoogleAuthProvider,onAuthStateChanged,signInWithEmailAndPassword,signInWithPopup,signOut,type User} from "firebase/auth";
import {doc,onSnapshot} from "firebase/firestore";
import {useEffect,useState} from "react";
import {auth,db} from "@/lib/firebase/client";
function allowed(data:Record<string,unknown>|undefined){return["owner","staff"].includes(String(data?.role??"").toLowerCase())}
function message(err:unknown){const code=typeof err==="object"&&err!==null&&"code"in err?String((err as {code?:unknown}).code):"";if(code==="auth/network-request-failed")return"Firebase could not be reached. Check your connection.";if(code==="auth/too-many-requests")return"Too many sign-in attempts. Wait a moment.";return err instanceof Error?err.message:"Sign-in could not be completed."}
export default function AdminGate({children}:{children:React.ReactNode}){const[user,setUser]=useState<User|null>(null),[checking,setChecking]=useState(true),[authorized,setAuthorized]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
useEffect(()=>{let stop:(()=>void)|undefined;const unsub=onAuthStateChanged(auth,next=>{stop?.();setUser(next);setChecking(true);if(!next){setAuthorized(false);setChecking(false);return}stop=onSnapshot(doc(db,"admins",next.uid),s=>{const ok=s.exists()&&allowed(s.data());setAuthorized(ok);setChecking(false);if(!ok)void signOut(auth)},()=>{setChecking(false);setAuthorized(false)})});return()=>{stop?.();unsub()}},[]);
async function finish(action:()=>Promise<User>){setBusy(true);setError("");try{const u=await action();const ok=await new Promise<boolean>(resolve=>{const stop=onSnapshot(doc(db,"admins",u.uid),s=>{stop();resolve(s.exists()&&allowed(s.data()))},()=>{stop();resolve(false)})});if(!ok){setError("This account is not enabled for the Atlas workshop dashboard. Add its UID to admins with role owner or staff.");await signOut(auth)}else setAuthorized(true)}catch(err){setError(message(err))}finally{setBusy(false)}}
if(checking)return <main className="adminPage"><div className="adminShell"><div className="emptyState">Checking Atlas workshop access…</div></div></main>;
if(user&&authorized)return <div className="adminAuthorized"><div className="adminAccountBar"><span>Atlas Workshop Control · {user.email??"authorized staff"}</span><button className="button buttonLight" onClick={()=>void signOut(auth)}>Sign out</button></div>{children}</div>;
return <main className="adminPage"><div className="adminShell"><section className="adminPanel loginCard"><span className="eyebrow">Atlas · Workshop</span><h1>Workshop sign in.</h1><p>Authorized owner/staff accounts only.</p><button className="button buttonPrimary" onClick={()=>void finish(async()=>(await signInWithPopup(auth,new GoogleAuthProvider())).user)} disabled={busy}>{busy?"Signing in…":"Continue with Google"}</button><div className="adminDivider">or</div><form className="adminForm" onSubmit={e=>{e.preventDefault();void finish(async()=>(await signInWithEmailAndPassword(auth,email.trim(),password)).user)}}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="button buttonLight" disabled={busy}>Sign in with email</button></form>{error&&<p className="notice" role="alert">{error}</p>}</section></div></main>}
