"use client";
import Link from "next/link";
import {GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged,type User} from "firebase/auth";
import {useEffect,useState} from "react";
import {auth} from "@/lib/firebase/client";
import {getCustomerProfile,getCustomerRequests,isAdminUser,saveCustomerProfile,type CustomerProfile,type ServiceRequest} from "@/lib/firebase/data";
export default function AccountPage(){const[user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<CustomerProfile|null>(null),[requests,setRequests]=useState<ServiceRequest[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
useEffect(()=>onAuthStateChanged(auth,async next=>{if(next&&await isAdminUser(next.uid)){await signOut(auth);return}setUser(next);if(next){const saved=await getCustomerProfile(next.uid).catch(()=>null);setProfile(saved??{uid:next.uid,name:next.displayName??"",email:next.email??"",phone:"",location:"",notes:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});setRequests(await getCustomerRequests(next.uid).catch(()=>[]))}else{setProfile(null);setRequests([])}}),[]);
async function google(){setBusy(true);setMessage("");try{const result=await signInWithPopup(auth,new GoogleAuthProvider());const saved=await getCustomerProfile(result.user.uid);if(saved)setProfile(saved);setMessage("Atlas account connected.")}catch(e){setMessage(e instanceof Error?e.message:"Google sign-in could not be completed.")}finally{setBusy(false)}}
async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!user||!profile)return;setBusy(true);const f=new FormData(e.currentTarget);const next={...profile,name:String(f.get("name")||"").trim(),email:String(f.get("email")||"").trim(),phone:String(f.get("phone")||"").trim(),location:String(f.get("location")||"").trim(),notes:String(f.get("notes")||"").trim(),updatedAt:new Date().toISOString()};try{await saveCustomerProfile(next);setProfile(next);setRequests(await getCustomerRequests(user.uid));setMessage("Your Atlas details are saved.")}catch{setMessage("We could not save your details.")}finally{setBusy(false)}}
return <main className="formPage"><div className="formWrap"><div className="formTop"><Link href="/" className="brand compact"><span className="brandBadge">ASC</span><span><strong>ATLAS SERVICE CENTRE</strong><small>Your Auto Mechanical & Electrical Specialists</small></span></Link><Link href="/book" className="button buttonPrimary">New request</Link></div><section className="formCard"><span className="eyebrow">Customer account</span><h1>Keep your service history close.</h1><p>Guest requests work without an account. Connecting Google lets Atlas associate future requests with your account.</p>{!user?<button className="button buttonPrimary" onClick={()=>void google()} disabled={busy}>Continue with Google</button>:profile&&<><p className="truthNote">Signed in as {profile.email||user.email||"Atlas customer"}.</p><form className="adminForm" onSubmit={save}><label>Name<input name="name" defaultValue={profile.name} required/></label><label>Email<input name="email" type="email" defaultValue={profile.email} readOnly={Boolean(user.email)} required/></label><label>Phone / WhatsApp<input name="phone" defaultValue={profile.phone} required/></label><label>Vehicle / usual location<input name="location" defaultValue={profile.location}/></label><label>Notes<textarea name="notes" defaultValue={profile.notes}/></label><button className="button buttonPrimary" disabled={busy}>{busy?"Saving…":"Save details"}</button></form><h2 className="accountHeading">My requests</h2>{requests.length?<div className="queue">{requests.map(r=><article className="queueRow" key={r.id}><div><strong>#{r.id.slice(0,8).toUpperCase()} · {r.service}</strong><small>{r.vehicle}{r.registration?" · "+r.registration:""} · {new Date(r.createdAt).toLocaleString()}</small></div><div className="queueActions"><strong>{r.status}</strong><Link className="button buttonLight" href={"/orders/"+r.id}>Track</Link></div></article>)}</div>:<p className="emptyState">No service requests on this account yet.</p>}<button className="button buttonLight" onClick={()=>void signOut(auth)}>Sign out</button></>}{message&&<p className="notice">{message}</p>}</section></div></main>}